In [58]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [59]:
#import winequality dataset and print first five columns
import pandas as pd
df = pd.read_csv('winequality.csv')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,8.94,0.507,0.29,0.90,0.031,7.8,21.9,0.9993,3.44,0.62,9.89,5
1,8.42,0.681,0.19,3.33,0.012,1.0,53.6,0.9953,3.36,1.10,11.77,6
2,9.65,0.362,0.35,2.24,0.159,21.4,62.2,0.9968,3.46,0.68,9.69,5
3,5.63,0.278,0.50,0.90,0.099,6.3,19.1,0.9952,3.50,0.72,10.90,6
4,6.49,0.474,0.59,6.77,0.142,19.3,44.9,0.9972,3.41,0.67,11.01,5

In [60]:
df.shape

(1607, 12)

In [61]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1607.000000,1607.000000,1607.000000,1607.000000,1595.000000,1607.000000,1607.000000,1607.000000,1592.000000,1588.000000,1607.000000,1607.000000
mean,8.291077,0.525606,0.282215,2.614051,0.091024,17.093404,47.845240,0.996706,3.319604,0.668734,10.438419,5.589297
std,1.682200,0.176942,0.179063,2.323494,0.044608,10.122153,21.154736,0.001824,0.150891,0.165679,1.072897,0.716700
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,2.000000,0.991100,2.780000,0.330000,8.400000,4.000000
25%,7.150000,0.407000,0.150000,0.900000,0.059000,9.100000,32.850000,0.995500,3.220000,0.550000,9.660000,5.000000
50%,8.290000,0.521000,0.270000,1.730000,0.090000,16.800000,47.000000,0.996700,3.320000,0.670000,10.410000,6.000000
75%,9.430000,0.639000,0.410000,3.285000,0.121000,24.100000,62.000000,0.997900,3.420000,0.780000,11.170000,6.000000
max,15.360000,1.075000,0.860000,15.500000,0.235000,53.200000,116.700000,1.001900,3.810000,1.210000,14.340000,8.000000

In [62]:
df.isnull().sum()

fixed acidity            0
volatile acidity         0
citric acid              0
residual sugar           0
chlorides               12
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                      15
sulphates               19
alcohol                  0
quality                  0
dtype: int64

In [63]:
# Features and target
X = df.drop("quality", axis=1)
y = df["quality"]

In [64]:
# Handle missing values
imputer = SimpleImputer(strategy="mean")
X = imputer.fit_transform(X)

In [65]:
# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42,stratify=y)

In [66]:
# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Train model
rf_model.fit(X_train, y_train)

# Predictions on test
y_pred = rf_model.predict(X_test)

#training accuracy
train_accuracy = model.score(X_train, y_train)

#testing accuracy
test_accuracy = accuracy_score(y_test,y_pred)

In [74]:
print("training Accuracy:",accuracy_score(y_test, y_pred))

training Accuracy: 0.577639751552795

In [73]:
print("testing Accuracy:",accuracy_score(y_test,y_pred) )

testing Accuracy: 0.577639751552795